#!/usr/bin/env python3
"""Real EasyTier integration, loopback only: no TUN, STUN or system changes.

Starts an isolated El Ciber client and a reference EasyTier peer. Uses a real
invitation internally without ever printing it. This is NOT a VPN/game test.
"""
import argparse
import base64
import json
import os
from pathlib import Path
import re
import socket
import subprocess
import tempfile
import time
import urllib.error
import urllib.request
import uuid

ROOT = Path(__file__).resolve().parents[1]
SAFE_ENV = {k: v for k, v in os.environ.items() if k in {"PATH", "HOME", "USERPROFILE", "SystemRoot", "SYSTEMROOT", "TEMP", "TMP", "LOCALAPPDATA", "APPDATA"}}


def free_port():
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


def net_snapshot():
    route = Path('/proc/net/route')
    interfaces = Path('/sys/class/net')
    return (route.read_bytes() if route.exists() else None,
            sorted(p.name for p in interfaces.iterdir()) if interfaces.exists() else None)


def stop(process):
    if process is None or process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=8)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=3)


def eventually(fn, timeout=15):
    end = time.monotonic() + timeout
    while time.monotonic() < end:
        try:
            value = fn()
            if value:
                return value
        except (OSError, urllib.error.URLError, json.JSONDecodeError):
            pass
        time.sleep(0.2)
    raise AssertionError('Bounded integration readiness failed')


def run(binary, engine_dir):
    if os.name != 'posix':
        raise ValueError('The no-TUN integration harness is currently validated on Linux only')
    core, cli = engine_dir / 'easytier-core', engine_dir / 'easytier-cli'
    for executable in [binary, core, cli]:
        if not executable.is_file():
            raise ValueError('Build El Ciber and fetch the pinned engine first')
    before = net_snapshot()
    app = reference = None
    with tempfile.TemporaryDirectory(prefix='elciber-integration-') as temp:
        temp = Path(temp)
        port, peer_port, rpc_port = free_port(), free_port(), free_port()
        base = f'http://127.0.0.1:{port}'
        opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
        try:
            app = subprocess.Popen([str(binary), '--listen', f'127.0.0.1:{port}', '--data-dir', str(temp / 'client'), '--engine-dir', str(engine_dir), '--no-browser'],
                                   env=SAFE_ENV, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            html = eventually(lambda: opener.open(base, timeout=2).read().decode())
            match = re.search(r'<meta name="elciber-token" content="([^"]+)"', html)
            if match is None:
                raise AssertionError('Session bootstrap missing')
            token = match.group(1)

            def api(path, method='GET', data=None):
                body = None if data is None else json.dumps(data).encode()
                request = urllib.request.Request(base + path, data=body, method=method, headers={
                    'X-Elciber-Token': token, 'Content-Type': 'application/json', 'Origin': base,
                })
                with opener.open(request, timeout=12) as response:
                    return json.load(response)

            print('Integration: local client ready.')
            room = api('/api/rooms', 'POST', {'name': 'Prueba local aislada', 'game': 'Integración sin TUN', 'rendezvous': f'tcp://127.0.0.1:{peer_port}', 'rendezvousKey': ''})
            invitation = api(f'/api/rooms/{room["id"]}/invite', 'POST', {})['invite']
            payload = invitation.removeprefix('elciber1:')
            private = json.loads(base64.urlsafe_b64decode(payload + '=' * (-len(payload) % 4)))
            # All data is newly generated by our isolated app; no personal rooms.
            config = '\n'.join([
                'instance_name = "elciber-reference"',
                f'instance_id = "{uuid.uuid4()}"',
                'hostname = "Peer-de-prueba"',
                'dhcp = false',
                f'listeners = ["tcp://127.0.0.1:{peer_port}"]',
                'stun_servers = []', 'stun_servers_v6 = []', 'exit_nodes = []', 'routes = []',
                '[network_identity]',
                f'network_name = "elciber-{private["id"]}"',
                f'network_secret = "{private["secret"]}"',
                '[secure_mode]', 'enabled = true',
                '[flags]', 'no_tun = true', 'enable_encryption = true', 'encryption_algorithm = "chacha20"', 'enable_ipv6 = false',
                'disable_p2p = true', 'disable_tcp_hole_punching = true', 'disable_udp_hole_punching = true',
                'disable_sym_hole_punching = true', 'disable_upnp = true', 'accept_dns = false',
                'relay_network_whitelist = ""', 'private_mode = true', 'enable_exit_node = false',
                'enable_udp_broadcast_relay = false', 'disable_relay_data = true',
            ])
            config_path = temp / 'reference.toml'
            fd = os.open(config_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
            with os.fdopen(fd, 'w') as output:
                output.write(config)
            reference = subprocess.Popen([str(core), '--config-file', str(config_path), '--secure-mode', 'true', '--rpc-portal', f'127.0.0.1:{rpc_port}', '--disable-env-parsing'],
                                         env=SAFE_ENV, cwd=temp, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

            def reference_ready():
                result = subprocess.run([str(cli), '-p', f'127.0.0.1:{rpc_port}', '-o', 'json', 'node', 'info'], env=SAFE_ENV, capture_output=True, timeout=3)
                return result.returncode == 0 and bool(json.loads(result.stdout).get('peer_id'))
            eventually(reference_ready)
            print('Integration: reference EasyTier RPC ready.')
            result = api('/api/connect', 'POST', {'roomId': room['id'], 'acknowledge': True})
            assert result.get('ok') is True
            print('Integration: client EasyTier RPC ready.')

            def connected():
                state = api('/api/state')
                return state if state['engine']['status'] == 'running' and any(p['hostname'] == 'Peer-de-prueba' for p in state['engine']['peers']) else None
            state = eventually(connected, 20)
            assert state['engine']['mode'] == 'inspection'
            assert not state['engine']['virtualIP']
            assert private['secret'] not in json.dumps(state)
            assert api('/api/disconnect', 'POST', {}).get('ok') is True
            eventually(lambda: api('/api/state')['engine']['status'] == 'stopped')
            assert api('/api/disconnect', 'POST', {}).get('ok') is True
            assert api('/api/quit', 'POST', {}).get('ok') is True
            app.wait(timeout=8)
            assert app.returncode == 0, 'Application did not close normally'
            app = None
            assert not list((temp / 'client').rglob('*.toml')), 'Runtime config not removed'
        finally:
            stop(app)
            stop(reference)
    assert net_snapshot() == before, 'Interfaces or routes changed during no-TUN test'
    print('PASS: real invitation → EasyTier secure peer → real presence → disconnect/cleanup.')
    print('PASS: interfaces/routes unchanged; loopback-only inspection. No LAN/game compatibility claimed.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--binary', type=Path, default=ROOT / 'dist' / 'elciber')
    parser.add_argument('--engine-dir', type=Path, default=ROOT / 'engines' / 'easytier')
    args = parser.parse_args()
    try:
        run(args.binary.resolve(), args.engine_dir.resolve())
    except Exception as error:
        # Avoid tracebacks containing invitation/config variables or raw subprocess output.
        import traceback
        frames = traceback.extract_tb(error.__traceback__)
        location = frames[-1] if frames else None
        step = f'{Path(location.filename).name}:{location.lineno}' if location else 'unknown'
        print(f'FAIL: {type(error).__name__} at {step}; real integration did not complete. No simulated fallback.')
        raise SystemExit(1)
